---
Label: &not_required
  default:
  required: False

# Connection Section
Connection:
  Username: *not_required
  Password: *not_required
  Authtype:
    default: Cyberark
    required: False
  AppID: *not_required
  User_Search: *not_required

# PVWA Section
PVWA:
  Host: &required
    required: True
  PWVA_CA:
    <<: *not_required
    alternate_names:
      - ca
      - verify
  timeout:
    default: <CYBERARK_DEFAULT_TIMEOUT>
  max_concurrent_tasks:
    default: <CYBERARK_DEFAULT_MAX_CONCURRENT_TASKS>
    alternate_names:
      - maxtasks

# AIM Section
AIM:
  AppID: *required
  Host: *required
  Cert: *required
  Key: *required
  AIM_CA:
    <<: *not_required
    alternate_names:
      - ca
      - verify
  timeout:
    default: <CYBERARK_DEFAULT_TIMEOUT>
  max_concurrent_tasks:
    default: <CYBERARK_DEFAULT_MAX_CONCURRENT_TASKS>
    alternate_names:
      - maxtasks
  User_Search:
    Safe: *required
    Object: *required

CPM: *not_required
CustomIPField: *not_required
Retention:
  default: <CYBERARK_DEFAULT_RETENTION>
  required: False

