name: Example workflow for Python using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./aiobastion
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./aiobastion/requirements.txt
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=aiobastion/requirements.txt --debug